// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ARWKDV9hnmreu0fxQ-qkhD2XLrinplk',
    appId: '1:633326049997:web:272ca0074f043cd2ff6784',
    messagingSenderId: '633326049997',
    projectId: 'note-it-eb06a',
    authDomain: 'note-it-eb06a.firebaseapp.com',
    storageBucket: 'note-it-eb06a.appspot.com',
    measurementId: 'G-R0KJ15K88R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXx1t_oXnPX1WCzZCxv_LS6xD1E1AD0mQ',
    appId: '1:633326049997:android:140d05e6de6ee9c3ff6784',
    messagingSenderId: '633326049997',
    projectId: 'note-it-eb06a',
    storageBucket: 'note-it-eb06a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaxX34R59OrP9dWobP7Hcvob8w_jcApKM',
    appId: '1:633326049997:ios:3e0371a868d8239dff6784',
    messagingSenderId: '633326049997',
    projectId: 'note-it-eb06a',
    storageBucket: 'note-it-eb06a.appspot.com',
    iosBundleId: 'com.example.noteIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaxX34R59OrP9dWobP7Hcvob8w_jcApKM',
    appId: '1:633326049997:ios:c47b01d6dc4b51d8ff6784',
    messagingSenderId: '633326049997',
    projectId: 'note-it-eb06a',
    storageBucket: 'note-it-eb06a.appspot.com',
    iosBundleId: 'com.example.noteIt.RunnerTests',
  );
}
